### ISSUE TITLE
Latest version 3.0.0 fails to install because of a regression in the future dependency

### ISSUE THREAD

**Issue by wilig** [cdent/paste#6] opened 2018-10-24 20:31 UTC
Trying to install the 3.0.0 version causes a loop in the future-0.16.0 installation.

Lots of this:
`
Writing /tmp/easy_install-qrquXV/future-0.16.0/setup.cfg
Running future-0.16.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qrquXV/future-0.16.0/egg-dist-tmp-ig1YZv
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
  yield
File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
  self.gen.throw(type, value, traceback)
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
  saved_exc.resume()
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
  six.reraise(type, exc, self._tb)
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
  yield saved
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
  yield
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
  _execfile(setup_script, ns)
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
  exec(code, globals, locals)
File "/tmp/easy_install-qrquXV/future-0.16.0/temp/easy_install-dr0htN/future-0.16.0/temp/easy_install-gkS28V/future-0.16.0/temp/easy_install-doSr4k/future-0.16.0/temp/easy_install-B6piFf/future-0.16.0/temp/easy_install-oUQLUx/future-0.16.0/temp/easy_install-pqGnNg/future-0.16.0/setup.py", line 186, in <module>
`
...

Followed eventually by:

`
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 419, in _open
  return _open(path, mode, *args, **kw)
File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 417, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
RuntimeError: maximum recursion depth exceeded in cmp
`

I can reproduce this with a clean install consistently.

**Comment by cdent** [comment] 2018-10-24 20:58
Thanks, will dig into this. I wonder why I didn't get this in my own testing.

And thanks for reporting it so quickly, I was hoping we'd break and fix things as quickly as possible.

**Comment by cdent** [comment] 2018-10-24 21:04
I'm going to need more information as I can't reproduce this in a clean virtualenv. Some questions:

* What version of python are you using?
* On what OS
* What command are you using to install Paste?

@bszonye could you add the same info here too?

**Comment by bszonye** [comment] 2018-10-24 21:09
I’m running my install in a docker container running an image built on `ubuntu:xenial` with `python2` and other packages installed. I’ll see if I can make a more minimal testcase.

**Comment by bszonye** [comment] 2018-10-24 21:11
The future-0.16.0 infinite loop _does_ happen if we install PasteScript==1.7.5 but _not_ if we install PasteScript==2.0.2 – my developers are checking to see if that’s a usable workaround for us, and I’m working on getting you a better testcase.

**Comment by bszonye** [comment] 2018-10-24 21:21
How to reproduce:```
docker run --rm -it ubuntu:xenial
apt update && apt install -y python python-pip
pip install PasteScript==1.7.5
```

**Comment by bszonye** [comment] 2018-10-24 21:28
Similar results with ubuntu:bionic (pip 9.0.1) and our custom build environment (pip 18.1).
```
pip install PasteScript==2.0.2
```
appears to work fine on all of them.

Thanks for the prompt response & investigation!

**Comment by cdent** [comment] 2018-10-24 21:28
Okay, as a short term workaround you can `pip install future && pip install PasteScript==1.7.5` and it will complete.

I think the easiest thing to do at this point is probably back out the changes I did to add in future. That was for the sake of using html.escape instead of cgi.escape.

**Comment by bszonye** [comment] 2018-10-24 21:33
Unfortunately we are using a build system that installs all requirements in one go from `requirements.txt` and that runs into the same problem as this:
```
pip install future PasteScript==1.7.5
```
because PasteScript tries to install `future` via setuptools/easy-install even before pip can install it at the top level. Luckily it looks like PasteScript 2.0.2 might also work for us as a workaround. Our engineers have confirmed that it 2.0.2 builds for them & they’re verifying the results.

**Comment by cdent** [comment] 2018-10-24 21:36
I should have a new version in a few minutes.

**Comment by wilig** [comment] 2018-10-24 21:45
Thanks for getting this sorted out so fast!

**Comment by bszonye** [comment] 2018-10-24 21:50
Yes, we really appreciate the prompt response!

**Comment by cdent** [comment] 2018-10-24 21:55
Okay, should be a 3.0.1 at https://pypi.org/p/Paste that doesn't use future at all. Please let me know how it goes. And don't be surprised if there are further issues ...

**Comment by bszonye** [comment] 2018-10-24 22:03
Thank you! It looks good in my minimal test case. I am talking to my devs for a test case (that didn’t already use my other workaround of upgrading to PasteScript 2.0.2).

**Comment by bszonye** [comment] 2018-10-24 22:12
Verified that this also fixes our application builds. Thanks again!

**Comment by cdent** [comment] 2018-10-24 22:15
Yay! I'm going to close this then, if something related comes up, please open it back up. Otherwise if you see some other bug, please open a new issue and I'll get to it ASAP (but not in the next 10 hours or so, it's bed time).

Thanks very much for the quick feedback, made it much easier to get to the root of the problem quickly.

**Closed by cdent** 2018-10-24 22:15 UTC
